Repository redhat-appstudio/tssc-cli, pull requests merged in 2024-09, with the labels that each got.

#189 RHTAPBUGS-1299: TPA MinIO Event Subscription
  charts/rhtap-infrastructure/Chart.yaml
  charts/rhtap-infrastructure/templates/kafka/kafkausers.yaml
  charts/rhtap-infrastructure/templates/minio/job-post-deploy.yaml
  charts/rhtap-infrastructure/templates/minio/service-account.yaml
  charts/rhtap-infrastructure/values.yaml
  charts/rhtap-tpa/values.yaml
Labels: bug, approved, lgtm

#190 [RHTAPBUGS-1305] Adds default username to github integration
  charts/rhtap-dh/templates/app-namespaces/github-auth.secret.yaml
Labels: approved, lgtm

#191 feat: update TPA to 1.1.2
  charts/rhtap-tpa/Chart.yaml
  charts/rhtap-tpa/charts/redhat-trusted-profile-analyzer-0.1.1.tgz
  charts/rhtap-tpa/charts/redhat-trusted-profile-analyzer-0.1.2.tgz
Labels: approved, lgtm

#176 [WIP] Adapt rhtap-cli to run e2e tests
  integration-tests/pipelines/rhtap-cli-e2e.yaml
  integration-tests/tasks/rhtap-install.yaml
Labels: lgtm, do-not-merge/work-in-progress

#195 Fix integration tests and add new oci-container to collect artifacts
  integration-tests/pipelines/rhtap-cli-e2e.yaml
  integration-tests/tasks/rhtap-install.yaml
Labels: approved, lgtm

#197 chore: Remove renaming from itg
  integration-tests/pipelines/rhtap-cli-e2e.yaml
  integration-tests/tasks/rhtap-install.yaml
Labels: do-not-merge/hold

#202 fix: create default user in Dockerconfig
  Dockerfile
Labels: approved, lgtm

#203 fix: copy targets in Dockerfile
  Dockerfile
Labels: approved, lgtm

#204 fix: add 'kubectl' to the image
  Dockerfile
  charts/rhtap-dh/hooks/post-deploy.sh
Labels: approved, lgtm

#214 feat: Container Image Build GitHub Action
  .github/actions/buildah/action.yaml
  .github/workflows/release.yaml
  CONTRIBUTING.md
  Makefile
Labels: approved, lgtm

#207 fix: get ocp clients from a trusted source
  Dockerfile
  installer/charts/rhtap-dh/hooks/post-deploy.sh
Labels: approved, lgtm

#213 feat: Add labels to cli image to avoid ec violations when we release
  .tekton/rhtap-cli-pull-request.yaml
  .tekton/rhtap-cli-push.yaml
  Dockerfile
Labels: approved

#220 feat: rhtap cli 1.2.0 container release preparations
  .tekton/rhtap-cli-pull-request.yaml
  .tekton/rhtap-cli-push.yaml
  Dockerfile
Labels: approved

#212 modify version to point to branch release-1.2
  .tekton/rhtap-cli-pull-request.yaml
  .tekton/rhtap-cli-push.yaml
Labels: approved, do-not-merge/hold

#218 feat: Add Red Hat labels and install kubectl from latest stable release
  .tekton/rhtap-cli-pull-request.yaml
  .tekton/rhtap-cli-push.yaml
  Dockerfile
Labels: approved, do-not-merge/hold

#230 feat: Use ose-tools for release-1.2 and enable hermetic builds
  .tekton/rhtap-cli-pull-request.yaml
  .tekton/rhtap-cli-push.yaml
  Dockerfile
Labels: approved, lgtm

#233 chore: prepare CI for github enterprise fix
  integration-tests/tasks/rhtap-install.yaml
Labels: approved, lgtm

#234 fix: typo in CI pipeline
  integration-tests/tasks/rhtap-install.yaml
Labels: approved, lgtm

#237 fix: ci install process
  integration-tests/tasks/rhtap-install.yaml
Labels: approved, lgtm

#248 fix: move CI install logic to a script
  integration-tests/scripts/install.sh
  integration-tests/scripts/minio.sh
  integration-tests/tasks/rhtap-install.yaml
Labels: approved
