Repository redhat-appstudio/tssc-cli, pull requests merged in 2024-08, with the labels that each got.

#155 fix to use correct repo and revision
  integration-tests/pipelines/rhtap-cli-e2e.yaml
Labels: approved, lgtm

#150 fix: get app URL from the manifest
  pkg/githubapp/githubapp.go
  pkg/githubapp/template.go
Labels: approved, lgtm

#151 fix: quay integration help
  pkg/integrations/quay.go
Labels: approved, lgtm

#154 feat: display TAS URLs for Jenkins config
  charts/rhtap-dh/templates/NOTES.txt
  charts/rhtap-tas/templates/tas-integration.secret.yaml
  charts/rhtap-tas/values.yaml
  charts/values.yaml.tpl
Labels: approved, lgtm

#158 fix: sanitize GH App URL
  pkg/githubapp/githubapp.go
Labels: approved, lgtm

#161 feat: update TPA to 1.1.1
  charts/rhtap-tpa/Chart.yaml
  charts/rhtap-tpa/charts/redhat-trusted-profile-analyzer-0.1.0.tgz
  charts/rhtap-tpa/charts/redhat-trusted-profile-analyzer-0.1.1.tgz
Labels: approved, lgtm

#162 RHTAPINST-120: GitHub Project Release
  .github/actions/go/action.yaml
  .github/workflows/release.yaml
  .goreleaser.yaml
  CONTRIBUTING.md
  Makefile
  README.md
Labels: approved, lgtm

#164 fix: improve charts output
  charts/rhtap-backing-services/templates/NOTES.txt
  charts/rhtap-dh/templates/NOTES.txt
Labels: approved, lgtm

#165 Fix integration tests pipeline
  integration-tests/pipelines/rhtap-cli-e2e.yaml
Labels: approved, lgtm

#171 added secret 'rhtap-cli-config' to fix rhtap-install
  integration-tests/tasks/rhtap-install.yaml
Labels: lgtm

#168 RHTAPBUGS-1294: More Storage by Default
  charts/rhtap-infrastructure/values.yaml
Labels: bug, approved, lgtm

#170 fix: Improve Charts Output
  charts/rhtap-backing-services/templates/NOTES.txt
  charts/rhtap-dh/templates/NOTES.txt
  pkg/subcmd/deploy.go
  scripts/test-subscriptions.sh
Labels: approved

#174 RHTAPINST-126: Multiple OS Support
  pkg/flags/flags.go
Labels: enhancement, approved, lgtm

#172 chore: Snyk Ignore File
  .snyk
Labels: approved, do-not-merge/hold

#175 Update subscription channels
  charts/rhtap-subscriptions/values.yaml
  scripts/test-subscriptions.sh
Labels: approved, lgtm

#177 fix: DH GitLab config
  charts/rhtap-dh/templates/app-config-content.yaml
  charts/rhtap-dh/templates/extra-env.yaml
  pkg/integrations/gitlab.go
  pkg/subcmd/integration_gitlab.go
Labels: approved, lgtm

#180 RHTAPBUGS-1299: TPA Bucket vs. Kafka Topics Configuration
  charts/rhtap-infrastructure/values.yaml
  charts/rhtap-tpa/values.yaml
Labels: bug, approved, lgtm

#182 fix: install with a different namespace prefix
  charts/rhtap-dh/hooks/post-deploy.sh
  charts/rhtap-dh/templates/app-namespaces/cosign-pub.secret.yaml
  charts/rhtap-dh/templates/app-namespaces/github-auth.secret.yaml
  charts/rhtap-dh/templates/app-namespaces/gitlab-auth.secret.yaml
  charts/rhtap-dh/templates/app-namespaces/namespaces.yaml
  charts/rhtap-dh/templates/app-namespaces/pipelines.secret.yaml
  charts/rhtap-dh/templates/app-namespaces/quay-auth.secret.yaml
  charts/rhtap-dh/templates/app-namespaces/rox-api-token.secret.yaml
  charts/rhtap-dh/templates/app-namespaces/tpa.secret.yaml
  charts/rhtap-dh/templates/extra-env.yaml
  charts/values.yaml.tpl
Labels: approved, lgtm

#184 Add default url for quay integration
  charts/rhtap-backing-services/templates/NOTES.txt
  charts/rhtap-dh/hooks/post-deploy.sh
  charts/rhtap-dh/templates/NOTES.txt
  charts/rhtap-infrastructure/templates/NOTES.txt
  charts/rhtap-integrations/templates/NOTES.txt
  charts/rhtap-tas/templates/NOTES.txt
  charts/rhtap-tpa/templates/NOTES.txt
  pkg/integrations/quay.go
Labels: approved, lgtm

#185 Add GitLab secret to ArgoCD namespace
  charts/rhtap-backing-services/templates/NOTES.txt
  charts/rhtap-backing-services/templates/openshift-gitops/gitlab-auth-secret.yaml
  charts/rhtap-tpa/templates/NOTES.txt
Labels: approved, lgtm

#187 Update README.md
  README.md
Labels: approved, ok-to-test, lgtm
