Repository redhat-appstudio/tssc-cli, pull requests merged in 2024-12, with the labels that each got.

#333 update templates to v1.3.0
  installer/config.yaml
Labels: approved, lgtm

#334 fixed the issues that static-code-analysis CI reported
  integration-tests/custom-resources/e2e-IntegrationTestScenario.yaml
  integration-tests/custom-resources/plrManager-Role.yaml
  integration-tests/custom-resources/plrManager-RoleBinding.yaml
  integration-tests/pipelines/e2e-main-pipeline.yaml
  integration-tests/pipelines/rhtap-cli-e2e.yaml
  integration-tests/scripts/install.sh
  integration-tests/scripts/minio.sh
  integration-tests/tasks/rhtap-install.yaml
Labels: lgtm

#340 RHTAPINST-189: Bringing Latest Changes to Release 1.3
  docs/container-image.md
  pkg/githubapp/githubapp.go
Labels: approved, lgtm

#341 RHTAPINST-186: GitHub Release Action vs. Container Image
  .github/actions/buildah/action.yaml
  .github/workflows/release.yaml
  Makefile
Labels: approved, lgtm

#300 install.sh: set vars from files only if needed
  integration-tests/scripts/install.sh
Labels: approved, lgtm

#349 chore: bump chart versions
  installer/charts/rhtap-acs/Chart.yaml
  installer/charts/rhtap-backing-services/Chart.yaml
  installer/charts/rhtap-dh/Chart.yaml
  installer/charts/rhtap-gitops/Chart.yaml
  installer/charts/rhtap-infrastructure/Chart.yaml
  installer/charts/rhtap-integrations/Chart.yaml
  installer/charts/rhtap-minio-operator/Chart.yaml
  installer/charts/rhtap-openshift/Chart.yaml
  installer/charts/rhtap-pipelines/Chart.yaml
  installer/charts/rhtap-quay/Chart.yaml
  installer/charts/rhtap-subscriptions/Chart.yaml
  installer/charts/rhtap-tas/Chart.yaml
  installer/charts/rhtap-tpa/Chart.yaml
Labels: approved, lgtm

#354 Adding rpms-signature-scan task to build pipeline
  .tekton/rhtap-cli-pull-request.yaml
  .tekton/rhtap-cli-push.yaml
Labels: approved, lgtm

#355 RHTAPINST-57: Show Global Values as YAML
  pkg/deployer/helm.go
  pkg/printer/printer.go
  pkg/subcmd/template.go
Labels: approved, lgtm

#357 feat: Upgrade to GitOps 1.15
  installer/charts/rhtap-subscriptions/values.yaml
Labels: approved, lgtm

#358 feat: add jq, oc binaries to the image
  Dockerfile
Labels: approved, lgtm

#359 RHTAPINST-133: Local and Embedded ChartFS
  integration-tests/scripts/install.sh
  pkg/chartfs/chartfs.go
  pkg/chartfs/chartfs_test.go
  pkg/flags/flags.go
  pkg/hooks/hooks_test.go
  pkg/subcmd/chartfs.go
  pkg/subcmd/deploy.go
  pkg/subcmd/installer.go
  pkg/subcmd/template.go
Labels: enhancement, approved, lgtm

#360 feat: Upgrade to Pipelines 1.17
  installer/charts/rhtap-subscriptions/values.yaml
Labels: approved, lgtm

#361 feat: Upgrade to TPA 1.2.1
  installer/charts/rhtap-tpa/Chart.yaml
  installer/charts/rhtap-tpa/charts/redhat-trusted-profile-analyzer-0.2.0.tgz
  installer/charts/rhtap-tpa/charts/redhat-trusted-profile-analyzer-0.2.1.tgz
Labels: approved, lgtm

#319 chore: fix some SonarQube issues
  pkg/engine/funcs_test.go
  pkg/subcmd/installer.go
Labels: approved, lgtm

#366 modified rhtap installation to accept the installation options generated by pict
  integration-tests/pict-models/default.pict
  integration-tests/pipelines/e2e-main-pipeline.yaml
  integration-tests/pipelines/rhtap-cli-e2e.yaml
  integration-tests/scripts/install.sh
  integration-tests/tasks/rhtap-install.yaml
Labels: lgtm
