Repository redhat-appstudio/tssc-cli, pull requests merged in 2024-11, with the labels that each got.

#295 fix: add missing plugin for GitLab CI
  installer/charts/rhtap-dh/templates/plugins-content.yaml
Labels: approved

#296 added bitbucket support in ci
  integration-tests/scripts/install.sh
Labels: approved, lgtm

#297 fix: plugin for GitLab CI
  installer/charts/rhtap-dh/templates/plugins-content.yaml
Labels: approved, lgtm

#301 RHTAPINST-152: Values-Template vs. Embedded Flags
  pkg/subcmd/deploy.go
  pkg/subcmd/template.go
Labels: bug, approved, lgtm

#304 RHTAPINST-140: Golang v1.22.5 and Container Images Update
  Dockerfile
  ci/Dockerfile
  go.mod
  vendor/github.com/rubenv/sql-migrate/test-migrations/1_initial.sql
  vendor/github.com/rubenv/sql-migrate/test-migrations/2_record.sql
Labels: approved, lgtm

#307 fix: lock amq-streams to 2.7
  installer/charts/rhtap-subscriptions/values.yaml
Labels: approved

#311 fix: bump rhtap-e2e image to support go 1.22
  integration-tests/tasks/rhtap-install.yaml
Labels: approved

#309 RHTAPINST-140: Go Builder Image v1.22.5
  Dockerfile
Labels: approved

#310 RHTAP-3321: Avoid race condition while patching
  installer/charts/rhtap-dh/hooks/post-deploy.sh
Labels: approved, lgtm

#313 feat: Upgrade to TPA 1.2.0
  installer/charts/rhtap-tpa/Chart.yaml
  installer/charts/rhtap-tpa/charts/redhat-trusted-profile-analyzer-0.1.2.tgz
  installer/charts/rhtap-tpa/charts/redhat-trusted-profile-analyzer-0.2.0.tgz
Labels: approved, lgtm

#312 fix: increase TPA storage
  installer/charts/rhtap-infrastructure/values.yaml
Labels: approved, lgtm

#316 RHTAPINST-184: Installer Payload Extraction
  pkg/subcmd/installer.go
Labels: approved, lgtm

#314 feat: Upgrade to TAS 1.1
  installer/charts/rhtap-subscriptions/values.yaml
Labels: approved, lgtm

#318 chore: fix some SonarQube issues
  Dockerfile
  ci/Dockerfile
  installer/charts/rhtap-integrations/templates/developer-hub/serviceaccount.yaml
  installer/charts/rhtap-integrations/templates/integrations/gitlab-integration.secret.yaml
  test/charts/testing/templates/configmap.yaml
Labels: approved, lgtm

#320 RHTAP-3332 Increase storage for guac
  installer/charts/rhtap-infrastructure/values.yaml
Labels: approved, lgtm

#322 RHTAPINST-181: MinIO Operator Namespace
  installer/charts/values.yaml.tpl
Labels: approved, lgtm

#325 updated plr to align with release-1.3
  .tekton/rhtap-cli-pull-request.yaml
  .tekton/rhtap-cli-push.yaml
Labels: approved, lgtm

#324 RHTAP-2558 - Setup dynamic e2e IntegrationTestingScenario
  integration-tests/README.md
  integration-tests/custom-resources/e2e-IntegrationTestScenario.yaml
  integration-tests/custom-resources/plrManager-Role.yaml
  integration-tests/custom-resources/plrManager-RoleBinding.yaml
  integration-tests/pict-models/default.pict
  integration-tests/pict-models/smoke.pict
  integration-tests/pipelines/e2e-main-pipeline.yaml
  integration-tests/pipelines/rhtap-cli-e2e.yaml
  integration-tests/tasks/rhtap-install.yaml
Labels: lgtm
