Repository redhat-appstudio/tssc-cli, pull requests merged in 2024-10, with the labels that each got.

#249 fix: ci
  integration-tests/scripts/install.sh
  integration-tests/tasks/rhtap-install.yaml
Labels: approved, lgtm

#250 fix: integrations chart must run before backing-services
  installer/config.yaml
Labels: approved, lgtm

#244 RHTAPINST-149: Wait for Operators Rollout
  installer/charts/rhtap-subscriptions/.helmignore
  installer/charts/rhtap-subscriptions/Chart.yaml
  installer/charts/rhtap-subscriptions/README.md
  installer/charts/rhtap-subscriptions/scripts/test-rollout-status.sh
  installer/charts/rhtap-subscriptions/templates/tests/test.yaml
Labels: approved, lgtm

#227 fix: github enterprise support
  installer/charts/rhtap-dh/templates/app-config-content.yaml
  installer/charts/rhtap-dh/templates/extra-env.yaml
  installer/charts/rhtap-integrations/templates/integrations/github-integration.secret.yaml
  installer/charts/values.yaml.tpl
  pkg/integrations/github.go
Labels: approved

#239 RHTAPINST-145: Windows Executable
  .goreleaser.yaml
  CONTRIBUTING.md
  Makefile
  README.md
Labels: approved, lgtm

#252 fix: allow kubectl and oc in DH post-hook
  installer/charts/rhtap-dh/hooks/post-deploy.sh
Labels: approved, lgtm

#251 fix: only create tarball when necessary
  Makefile
Labels: approved, lgtm

#224 feat: add 1.2 tag for latest 1.2.x changes
  .tekton/rhtap-cli-push.yaml
Labels: approved, lgtm

#232 RHTAPINST-99: Upstream MinIO Operator
  Makefile
  installer/charts/rhtap-infrastructure/Chart.yaml
  installer/charts/rhtap-infrastructure/templates/minio/job-post-deploy.yaml
  installer/charts/rhtap-minio-operator/.helmignore
  installer/charts/rhtap-minio-operator/CONTRIBUTING.md
  installer/charts/rhtap-minio-operator/Chart.yaml
  installer/charts/rhtap-minio-operator/README.md
  installer/charts/rhtap-minio-operator/charts/operator-5.0.17.tgz
  installer/charts/rhtap-minio-operator/scripts/test-rollout-status.sh
  installer/charts/rhtap-minio-operator/scripts/test-subscriptions.sh
  installer/charts/rhtap-minio-operator/templates/NOTES.txt
  installer/charts/rhtap-minio-operator/templates/_helpers.tpl
  installer/charts/rhtap-minio-operator/templates/_minio.tpl
  installer/charts/rhtap-minio-operator/templates/securitycontextcontraints.yaml
  installer/charts/rhtap-minio-operator/templates/tests/test.yaml
  installer/charts/rhtap-minio-operator/values.yaml
  installer/charts/rhtap-subscriptions/Chart.yaml
  installer/charts/rhtap-subscriptions/values.yaml
  installer/charts/values.yaml.tpl
  installer/config.yaml
  integration-tests/scripts/minio.sh
Labels: enhancement, approved, lgtm

#253 feat: upgrade OpenShift Pipelines to 1.15
  installer/charts/rhtap-subscriptions/values.yaml
Labels: approved, lgtm

#245 feat: give the GitHub App full access to Workflows
  pkg/integrations/github.go
Labels: approved, lgtm

#254 fix: increase quay storage
  installer/charts/rhtap-infrastructure/values.yaml
Labels: approved, lgtm

#243 feat: upgrade to OpenShift GitOps 1.14
  installer/charts/rhtap-subscriptions/values.yaml
Labels: approved, lgtm

#255 fix: generate tarball on content change
  Makefile
Labels: approved, lgtm

#258 fix: Avoid `.__*` Files on macOS
  CONTRIBUTING.md
  Makefile
Labels: bug, approved, lgtm

#257 feat: spin gitops/pipelines out of backing-services
  installer/charts/rhtap-backing-services/templates/NOTES.txt
  installer/charts/rhtap-backing-services/templates/tests/test.yaml
  installer/charts/rhtap-gitops/.helmignore
  installer/charts/rhtap-gitops/Chart.yaml
  installer/charts/rhtap-gitops/scripts/argocd-helper.sh
  installer/charts/rhtap-gitops/scripts/test-rollout-status.sh
  installer/charts/rhtap-gitops/templates/NOTES.txt
  installer/charts/rhtap-gitops/templates/_argocd.tpl
  installer/charts/rhtap-gitops/templates/_copy-scripts.tpl
  installer/charts/rhtap-gitops/templates/_helpers.tpl
  installer/charts/rhtap-gitops/templates/argocd.yaml
  installer/charts/rhtap-gitops/templates/gitlab-auth-secret.yaml
  installer/charts/rhtap-gitops/templates/job-post-deploy.yaml
  installer/charts/rhtap-gitops/templates/service-account.yaml
  installer/charts/rhtap-gitops/templates/tests/test.yaml
  installer/charts/rhtap-gitops/values.yaml
  installer/charts/rhtap-pipelines/.helmignore
  installer/charts/rhtap-pipelines/Chart.yaml
  installer/charts/rhtap-pipelines/templates/NOTES.txt
  installer/charts/rhtap-pipelines/templates/_helpers.tpl
  installer/charts/rhtap-pipelines/templates/job.yaml
  installer/charts/rhtap-pipelines/templates/pipelines-as-code-secret.yaml
  installer/charts/rhtap-pipelines/templates/service-account.yaml
  installer/charts/rhtap-pipelines/templates/tektonconfig.tpl
  installer/charts/rhtap-pipelines/values.yaml
  installer/charts/values.yaml.tpl
  installer/config.yaml
Labels: approved, lgtm

#256 customize RHTAP installation
  integration-tests/pipelines/rhtap-cli-e2e.yaml
  integration-tests/scripts/install.sh
  integration-tests/tasks/rhtap-install.yaml
Labels: approved, lgtm

#261 fix the issue of disabling ACS and Quay installation
  integration-tests/scripts/install.sh
Labels: approved, lgtm

#262 fix the issue when Quay is not installed as part of rhtap
  integration-tests/scripts/install.sh
Labels: approved, lgtm

#266 fix the issue of sprayproxy-deprovision
  integration-tests/pipelines/rhtap-cli-e2e.yaml
Labels: approved, ok-to-test, lgtm

#263 feat: upgrade OpenShift Pipelines to 1.16
  installer/charts/rhtap-subscriptions/values.yaml
Labels: approved

#267 feat: spin Quay out of backing-services
  installer/charts/rhtap-backing-services/scripts/quay-helper.sh
  installer/charts/rhtap-backing-services/templates/NOTES.txt
  installer/charts/rhtap-backing-services/templates/openshift-quay/quay-config-secret.yaml
  installer/charts/rhtap-backing-services/templates/openshift-quay/service-account.yaml
  installer/charts/rhtap-backing-services/templates/tests/test.yaml
  installer/charts/rhtap-backing-services/values.yaml
  installer/charts/rhtap-quay/.helmignore
  installer/charts/rhtap-quay/Chart.yaml
  installer/charts/rhtap-quay/scripts/quay-helper.sh
  installer/charts/rhtap-quay/scripts/test-rollout-status.sh
  installer/charts/rhtap-quay/templates/NOTES.txt
  installer/charts/rhtap-quay/templates/_copy-scripts.tpl
  installer/charts/rhtap-quay/templates/_helpers.tpl
  installer/charts/rhtap-quay/templates/_quay.tpl
  installer/charts/rhtap-quay/templates/job-quay-integration.yaml
  installer/charts/rhtap-quay/templates/quay-admin-secret.yaml
  installer/charts/rhtap-quay/templates/quay-config-secret.yaml
  installer/charts/rhtap-quay/templates/quayregistry.yaml
  installer/charts/rhtap-quay/templates/service-account.yaml
  installer/charts/rhtap-quay/templates/tests/test.yaml
  installer/charts/rhtap-quay/values.yaml
  installer/charts/values.yaml.tpl
  installer/config.yaml
Labels: approved

#270 Updated the --help output for integrate quay in rhtap-cli
  pkg/subcmd/integration_quay.go
Labels: approved, lgtm

#271 fix: create token for serviceaccount
  installer/charts/rhtap-dh/templates/extra-env.yaml
  installer/charts/rhtap-integrations/templates/developer-hub/serviceaccount.yaml
Labels: approved

#247 RHTAPINST-137: Nexus integration with rhtap
  installer/charts/rhtap-dh/hooks/post-deploy.sh
  installer/charts/rhtap-dh/templates/app-config-content.yaml
  installer/charts/rhtap-dh/templates/app-namespaces/nexus-auth.secret.yaml
  installer/charts/rhtap-dh/templates/extra-env.yaml
  pkg/integrations/nexus.go
  pkg/subcmd/integration.go
  pkg/subcmd/integration_nexus.go
Labels: approved, lgtm

#228 feat: Use ose-tools to get kubectl and enable hermetic builds
  .tekton/rhtap-cli-pull-request.yaml
  .tekton/rhtap-cli-push.yaml
  Dockerfile
Labels: approved

#275 RHTAPINST-139: Integrate artifactory into rhtap
  installer/charts/rhtap-dh/hooks/post-deploy.sh
  installer/charts/rhtap-dh/templates/app-config-content.yaml
  installer/charts/rhtap-dh/templates/app-namespaces/artifactory-auth.secret.yaml
  installer/charts/rhtap-dh/templates/extra-env.yaml
  pkg/integrations/artifactory.go
  pkg/subcmd/integration.go
  pkg/subcmd/integration_artifactory.go
Labels: approved, lgtm

#276 Fix nexus api endpoint
  installer/charts/rhtap-dh/templates/app-config-content.yaml
Labels: approved, lgtm

#274 a minior update for install.sh
  integration-tests/scripts/install.sh
  integration-tests/tasks/rhtap-install.yaml
Labels: approved, lgtm

#280 fix: ci rhtap-install script
  integration-tests/tasks/rhtap-install.yaml
Labels: approved

#278 Enable Nexus and Jfrog Artifactory plugin
  installer/charts/rhtap-dh/templates/plugins.yaml
Labels: approved, lgtm

#272 feat: Upgrade to Developer Hub 1.3
  installer/charts/rhtap-dh/templates/app-config-content.yaml
  installer/charts/rhtap-dh/templates/extra-env.yaml
  installer/charts/rhtap-dh/templates/plugins-content.yaml
  installer/charts/rhtap-dh/templates/plugins.yaml
  installer/charts/rhtap-subscriptions/values.yaml
Labels: approved, lgtm

#281 RHTAPBUGS-1355 Add token to RHDH GitHub app-config.yaml
  installer/charts/rhtap-dh/templates/app-config-content.yaml
  installer/charts/rhtap-dh/templates/extra-env.yaml
Labels: approved, lgtm

#285 feat: Upgrade to ACS 4.5
  installer/charts/rhtap-subscriptions/values.yaml
Labels: approved

#286 feat: Upgrade to Quay 3.12
  installer/charts/rhtap-subscriptions/values.yaml
Labels: approved

#289 feat: Enable GH/GL CI plugins in DH
  installer/charts/rhtap-dh/templates/plugins-content.yaml
Labels: approved

#291 feat: BitBucket Cloud integration
  installer/charts/rhtap-dh/templates/NOTES.txt
  installer/charts/rhtap-dh/templates/app-config-content.yaml
  installer/charts/rhtap-dh/templates/app-namespaces/bitbucket-auth.secret.yaml
  installer/charts/rhtap-dh/templates/extra-env.yaml
  installer/charts/rhtap-gitops/templates/bitbucket-auth-secret.yaml
  installer/charts/rhtap-integrations/templates/integrations/bitbucket-integration.secret.yaml
  pkg/integrations/bitbucket.go
  pkg/subcmd/integration.go
  pkg/subcmd/integration_bitbucket.go
Labels: approved

#294 feat: Upgrade to Quay 3.13
  installer/charts/rhtap-subscriptions/values.yaml
Labels: approved
