Repository redhat-appstudio/tssc-cli, pull requests merged in 2025-05, with the labels that each got.

#717 feat: Upgrade TAS to 1.2
  installer/charts/rhtap-dh/templates/extra-env.yaml
  installer/charts/rhtap-subscriptions/values.yaml
  installer/charts/rhtap-tas/Chart.yaml
Labels: approved, lgtm

#698 Migrating quay storage from Minio to ODF (Noobaa)
  installer/charts/rhtap-infrastructure/templates/odf/backing-store.yaml
  installer/charts/rhtap-infrastructure/templates/odf/enable-odf-console-plugin.yaml
  installer/charts/rhtap-infrastructure/templates/odf/noobaa.yaml
  installer/charts/rhtap-infrastructure/templates/odf/patch-default-bucketclass.yaml
  installer/charts/rhtap-infrastructure/templates/odf/post-install-hooks-rbac.yaml
  installer/charts/rhtap-infrastructure/values.yaml
  installer/charts/rhtap-openshift/templates/projects.yaml
  installer/charts/rhtap-quay/templates/_quay.tpl
  installer/charts/rhtap-quay/templates/quayregistry.yaml
  installer/charts/rhtap-quay/values.yaml
  installer/charts/rhtap-subscriptions/values.yaml
  installer/charts/values.yaml.tpl
Labels: approved, lgtm

#706 RHTAP-4382 - Add the cert to ACS central additionalCAs.
  installer/charts/rhtap-acs/templates/acs-central.yaml
  installer/charts/values.yaml.tpl
Labels: approved, lgtm

#725 RHTAP-4898 Add OpenShift 4.18 in CI
  integration-tests/pict-models/default.pict
  integration-tests/pict-models/smoke.pict
Labels: approved, lgtm

#719 fix: add /licenses folder to image
  Dockerfile
Labels: approved, lgtm

#726 feat: enable multi-ci plugin in DH
  installer/charts/rhtap-dh/templates/dynamic-plugins-registry-auth.yaml
  installer/charts/rhtap-dh/templates/plugins-content.yaml
Labels: approved, lgtm

#684 Read-only credentials for the development namespaces
  installer/charts/rhtap-app-namespaces/templates/secrets/image-registry-auth.yaml
  installer/charts/rhtap-quay/templates/job-quay-integration.yaml
  installer/charts/rhtap-quay/values.yaml
  installer/scripts/quay-helper.sh
  pkg/integrations/quay.go
  pkg/subcmd/integration_quay.go
Labels: approved, lgtm

#733 Replacing leaked password with info message about the login action
  integration-tests/scripts/ci-oc-login.sh
Labels: approved, lgtm

#737 disabled debug mode to avoid intall task showing sensitive data in the logs
  integration-tests/scripts/install.sh
Labels: approved, lgtm

#728 feat: rename binary to 'tssc'
  .gitignore
  .goreleaser.yaml
  CONTRIBUTING.md
  Dockerfile
  Makefile
  README.md
  cmd/ssc/main.go
  docs/container-image.md
  hack/deploy.sh
  integration-tests/scripts/install.sh
  pkg/cmd/root.go
  pkg/constants/contants.go
  pkg/subcmd/config.go
  pkg/subcmd/config_helper.go
  pkg/subcmd/deploy.go
  pkg/subcmd/installer.go
  pkg/subcmd/integration_quay.go
  pkg/subcmd/template.go
  test/charts/testing/Chart.yaml
Labels: approved, lgtm

#745 fix: ignore deleted repos in GitLab
  hack/reset.sh
Labels: approved

#744 Changing our tssc help RHTAP text to TSSC
  cmd/tssc/main.go
  pkg/subcmd/deploy.go
  pkg/subcmd/integration.go
  pkg/subcmd/integration_acs.go
  pkg/subcmd/integration_artifactory.go
  pkg/subcmd/integration_azure.go
  pkg/subcmd/integration_bitbucket.go
  pkg/subcmd/integration_githubapp.go
  pkg/subcmd/integration_gitlab.go
  pkg/subcmd/integration_jenkins.go
  pkg/subcmd/integration_nexus.go
  pkg/subcmd/integration_quay.go
  pkg/subcmd/integration_trustification.go
  pkg/subcmd/template.go
Labels: approved, lgtm

#739 Decrease the chance of CI failure due to TektonConfig cr being there
  installer/charts/rhtap-subscriptions/templates/openshift-pipelines/delete_tekton_config.yaml
  installer/charts/rhtap-subscriptions/templates/openshift-pipelines/post-install-hook-rbac.yaml
Labels: approved, lgtm

#771 CLOUDWF-11058: PGBackRest Container Image
  installer/charts/rhtap-infrastructure/templates/postgres/postgresclusters.yaml
  installer/charts/rhtap-infrastructure/values.yaml
Labels: approved, lgtm, do-not-merge/hold

#787 fix: fix config.yaml path in deploy.sh
  hack/deploy.sh
Labels: approved

#781 feat: Upgrade DH to 1.6
  installer/charts/tssc-subscriptions/values.yaml
Labels: approved, lgtm

#791 fix: lock rhtap-e2e revision
  integration-tests/pipelines/rhtap-cli-e2e.yaml
Labels: approved

#812 fix: TektonConfig workaround was broken by tssc renaming
  installer/charts/tssc-subscriptions/templates/openshift-pipelines/delete_tekton_config.yaml
  installer/charts/tssc-subscriptions/templates/openshift-pipelines/post-install-hook-rbac.yaml
Labels: approved

#811 RHTAP-5175: Crunchy Data Operator RBAC
  installer/charts/tssc-subscriptions/templates/crunchy-data-rbac.yaml
Labels: approved, lgtm

#790 RHTAP-4553: `tssc config` Subcommand vs. Global Flags (`--dry-run`)
  pkg/cmd/root.go
  pkg/config/manager.go
  pkg/subcmd/config.go
Labels: approved, lgtm

#792 feat: tssc renaming
  CONTRIBUTING.md
  README.md
  docs/container-image.md
  hack/ci-set-org-vars.sh
  hack/deploy.sh
  hack/reset.sh
  installer/charts/tssc-acs-test/Chart.yaml
  installer/charts/tssc-acs/Chart.yaml
  installer/charts/tssc-backing-services/Chart.yaml
  installer/charts/tssc-backing-services/README.md
  installer/charts/tssc-dh/templates/plugins-content.yaml
  installer/charts/tssc-gitops/Chart.yaml
  installer/charts/tssc-infrastructure/Chart.yaml
  installer/charts/tssc-infrastructure/templates/openshift-pipelines/tektonconfig/default._tpl
  installer/charts/tssc-infrastructure/templates/openshift-pipelines/tektonconfig/patch._tpl
  installer/charts/tssc-integrations/Chart.yaml
  installer/charts/tssc-minio-operator/Chart.yaml
  installer/charts/tssc-openshift/Chart.yaml
  installer/charts/tssc-openshift/README.md
  installer/charts/tssc-pipelines/Chart.yaml
  installer/charts/tssc-quay/Chart.yaml
  installer/charts/tssc-subscriptions/Chart.yaml
  installer/charts/tssc-subscriptions/README.md
  installer/charts/tssc-tpa/CONTRIBUTING.md
  installer/charts/tssc-tpa/Chart.yaml
  installer/scripts/acs-integration-helper.sh
  installer/scripts/stackrox-helper.sh
  integration-tests/README.md
  integration-tests/pipelines/rhtap-cli-e2e.yaml
  integration-tests/scripts/README.md
  integration-tests/scripts/install.sh
  integration-tests/tasks/rhtap-install.yaml
  pkg/deployer/openshift.go
  pkg/integrations/artifactory.go
  pkg/integrations/azure.go
  pkg/integrations/bitbucket.go
  pkg/integrations/github.go
  pkg/integrations/gitlab.go
  pkg/integrations/jenkins.go
  pkg/integrations/nexus.go
  pkg/integrations/quay.go
  pkg/integrations/trustification.go
  pkg/k8s/openshift.go
Labels: approved, lgtm

#746 fix: SonarCloud issues
  ci/Dockerfile
  hack/ci-set-org-vars.sh
  installer/scripts/test-acs-image-scan.sh
Labels: approved

#763 RHTAP-2871: Update rhtap-install task to set DH catalog url from tssc-sample-templates repo
  integration-tests/tasks/rhtap-install.yaml
Labels: approved, ok-to-test, lgtm

#816 feat: Remove Kafka/minIO operators
  installer/charts/tssc-infrastructure/scripts/test-kafka-topics.sh
  installer/charts/tssc-infrastructure/templates/NOTES.txt
  installer/charts/tssc-infrastructure/templates/kafka/_kafka.tpl
  installer/charts/tssc-infrastructure/templates/kafka/kafkas.yaml
  installer/charts/tssc-infrastructure/templates/kafka/kafkatopics.yaml
  installer/charts/tssc-infrastructure/templates/kafka/kafkausers.yaml
  installer/charts/tssc-infrastructure/templates/kafka/networkpolicies.yaml
  installer/charts/tssc-infrastructure/templates/minio/_minio.tpl
  installer/charts/tssc-infrastructure/templates/minio/job-post-deploy.yaml
  installer/charts/tssc-infrastructure/templates/minio/networkpolicies.yaml
  installer/charts/tssc-infrastructure/templates/minio/route.yaml
  installer/charts/tssc-infrastructure/templates/minio/secrets.yaml
  installer/charts/tssc-infrastructure/templates/minio/securitycontextconstraints.yaml
  installer/charts/tssc-infrastructure/templates/minio/service-account.yaml
  installer/charts/tssc-infrastructure/templates/minio/tenants.yaml
  installer/charts/tssc-infrastructure/templates/tests/test.yaml
  installer/charts/tssc-infrastructure/values.yaml
  installer/charts/tssc-minio-operator/.helmignore
  installer/charts/tssc-minio-operator/CONTRIBUTING.md
  installer/charts/tssc-minio-operator/Chart.yaml
  installer/charts/tssc-minio-operator/README.md
  installer/charts/tssc-minio-operator/charts/operator-5.0.17.tgz
  installer/charts/tssc-minio-operator/scripts/test-rollout-status.sh
  installer/charts/tssc-minio-operator/scripts/test-subscriptions.sh
  installer/charts/tssc-minio-operator/templates/NOTES.txt
  installer/charts/tssc-minio-operator/templates/_copy-scripts.tpl
  installer/charts/tssc-minio-operator/templates/_helpers.tpl
  installer/charts/tssc-minio-operator/templates/_minio.tpl
  installer/charts/tssc-minio-operator/templates/securitycontextcontraints.yaml
  installer/charts/tssc-minio-operator/templates/tests/_test.tpl
  installer/charts/tssc-minio-operator/templates/tests/test.yaml
  installer/charts/tssc-minio-operator/values.yaml
  installer/charts/tssc-subscriptions/values.yaml
  installer/charts/values.yaml.tpl
  installer/config.yaml
  installer/scripts/test-kafka-topics.sh
  integration-tests/scripts/minio.sh
  integration-tests/tasks/rhtap-install.yaml
Labels: approved, lgtm

#817 feat: add a 'settings' section to 'config.yaml'
  README.md
  installer/charts/values.yaml.tpl
  installer/config.yaml
  pkg/config/config.go
  pkg/engine/engine_test.go
Labels: approved, lgtm

#825 fix: SonarQube issues
  installer/charts/tssc-subscriptions/templates/openshift-pipelines/delete_tekton_config.yaml
Labels: approved, lgtm
