Repository redhat-appstudio/tssc-cli, pull requests merged in 2025-01, with the labels that each got.

#370 added missing parameter 'auth_config'
  integration-tests/pict-models/default.pict
  integration-tests/pipelines/rhtap-cli-e2e.yaml
  integration-tests/tasks/rhtap-install.yaml
Labels: approved, lgtm

#369 RHTAP-3384: Singleton ChartFS
  cmd/rhtap-cli/main.go
  pkg/chartfs/chartfs.go
  pkg/chartfs/chartfs_test.go
  pkg/cmd/root.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/engine/engine_test.go
  pkg/installer/installer.go
  pkg/subcmd/deploy.go
  pkg/subcmd/template.go
Labels: bug, approved, lgtm

#368 fix: RHTAP-3416 'template' command uses the wrong namespace
  installer/charts/rhtap-dh/values.yaml
  pkg/chartfs/chartfs.go
  pkg/config/config.go
  pkg/deployer/helm.go
  pkg/subcmd/template.go
Labels: approved, lgtm

#299 Update ACS to 4.6 and enable scannerV4
  installer/charts/rhtap-acs-scanner/.helmignore
  installer/charts/rhtap-acs-scanner/Chart.yaml
  installer/charts/rhtap-acs-scanner/README.md
  installer/charts/rhtap-acs-scanner/scripts/test-acs-image-scan.sh
  installer/charts/rhtap-acs-scanner/templates/NOTES.txt
  installer/charts/rhtap-acs-scanner/templates/_copy-scripts.tpl
  installer/charts/rhtap-acs-scanner/templates/_helpers.tpl
  installer/charts/rhtap-acs-scanner/templates/tests/test.yaml
  installer/charts/rhtap-acs-scanner/values.yaml
  installer/charts/rhtap-acs/templates/acs-central.yaml
  installer/charts/rhtap-acs/templates/tests/test.yaml
  installer/charts/rhtap-subscriptions/values.yaml
  installer/config.yaml
  installer/scripts/test-acs-image-scan.sh
Labels: approved, lgtm

#367 Do not stream logs. Print URL to nested PLR instead.
  integration-tests/pipelines/e2e-main-pipeline.yaml
Labels: approved, lgtm

#371 added support for nexus and artifacory
  integration-tests/pict-models/default.pict
  integration-tests/pict-models/smoke.pict
  integration-tests/scripts/.ci-env
  integration-tests/scripts/.env.template
  integration-tests/scripts/README.md
  integration-tests/scripts/install.sh
  integration-tests/tasks/rhtap-install.yaml
Labels: approved, lgtm

#378 removed sbom-json-check task because it's deprecated
  .tekton/rhtap-cli-pull-request.yaml
  .tekton/rhtap-cli-push.yaml
Labels: approved, lgtm

#385 feat: split DH instance config and gitops target namespaces
  installer/charts/rhtap-app-namespaces/.helmignore
  installer/charts/rhtap-app-namespaces/Chart.yaml
  installer/charts/rhtap-app-namespaces/hooks/post-deploy.sh
  installer/charts/rhtap-app-namespaces/templates/NOTES.txt
  installer/charts/rhtap-app-namespaces/templates/_helpers.tpl
  installer/charts/rhtap-app-namespaces/templates/namespaces.yaml
  installer/charts/rhtap-app-namespaces/templates/secrets/artifactory-auth.yaml
  installer/charts/rhtap-app-namespaces/templates/secrets/bitbucket-auth.yaml
  installer/charts/rhtap-app-namespaces/templates/secrets/cosign-pub.yaml
  installer/charts/rhtap-app-namespaces/templates/secrets/github-auth.yaml
  installer/charts/rhtap-app-namespaces/templates/secrets/gitlab-auth.yaml
  installer/charts/rhtap-app-namespaces/templates/secrets/nexus-auth.yaml
  installer/charts/rhtap-app-namespaces/templates/secrets/pipelines.yaml
  installer/charts/rhtap-app-namespaces/templates/secrets/quay-auth.yaml
  installer/charts/rhtap-app-namespaces/templates/secrets/rox-api-token.yaml
  installer/charts/rhtap-app-namespaces/templates/secrets/tpa.yaml
  installer/charts/rhtap-app-namespaces/values.yaml
  installer/config.yaml
Labels: approved, lgtm

#384 Fix: Fail pipelinerun if any of nested pipelines fails.
  integration-tests/pipelines/e2e-main-pipeline.yaml
Labels: approved, lgtm

#386 fix: RHTAP-3385 Add support for KUBECONFIG env var
  pkg/flags/flags.go
Labels: approved, lgtm

#394 feat: Upgrade to Developer Hub 1.4
  installer/charts/rhtap-dh/templates/app-config.yaml
  installer/charts/rhtap-dh/templates/backstage.yaml
  installer/charts/rhtap-dh/templates/extra-env.yaml
  installer/charts/rhtap-dh/templates/plugins-content.yaml
  installer/charts/rhtap-dh/templates/plugins.yaml
  installer/charts/rhtap-subscriptions/values.yaml
Labels: approved, lgtm

#391 modify parameters to adapt the rhtap-e2e-tests task
  integration-tests/pipelines/rhtap-cli-e2e.yaml
Labels: approved

#395 RHTAP-4018 Update plugins-content.yaml for Jenkins plugins
  installer/charts/rhtap-dh/templates/plugins-content.yaml
Labels: approved, lgtm

#397 chore: bump version of modified charts
  installer/charts/rhtap-acs-scanner/Chart.yaml
  installer/charts/rhtap-acs/Chart.yaml
  installer/charts/rhtap-app-namespaces/Chart.yaml
  installer/charts/rhtap-dh/Chart.yaml
  installer/charts/rhtap-infrastructure/Chart.yaml
  installer/charts/rhtap-subscriptions/Chart.yaml
Labels: approved, lgtm

#398 feat: Upgrade to TPA 1.2.2
  installer/charts/rhtap-tpa/Chart.yaml
  installer/charts/rhtap-tpa/charts/redhat-trusted-profile-analyzer-0.2.1.tgz
  installer/charts/rhtap-tpa/charts/redhat-trusted-profile-analyzer-0.2.2.tgz
Labels: approved, lgtm

#399 feat: Upgrade templates to 1.4.0
  installer/config.yaml
Labels: approved

#400 chore: Update all charts to version 1.4.0
  installer/charts/rhtap-backing-services/Chart.yaml
  installer/charts/rhtap-gitops/Chart.yaml
  installer/charts/rhtap-integrations/Chart.yaml
  installer/charts/rhtap-minio-operator/Chart.yaml
  installer/charts/rhtap-openshift/Chart.yaml
  installer/charts/rhtap-pipelines/Chart.yaml
  installer/charts/rhtap-quay/Chart.yaml
  installer/charts/rhtap-tas/Chart.yaml
Labels: approved, lgtm

#401 chore: update PLR to setup Konflux for release-1.4
  .tekton/rhtap-cli-pull-request.yaml
  .tekton/rhtap-cli-push.yaml
Labels: approved, lgtm

#404 feat: Enable the deployment of a single chart
  pkg/subcmd/deploy.go
Labels: approved, lgtm

#410 chore: Kafka Storage and Topics Retention
  installer/charts/rhtap-infrastructure/Chart.yaml
  installer/charts/rhtap-infrastructure/values.yaml
Labels: approved, lgtm

#411 fix: remove unused secrets from some namespaces
  installer/charts/rhtap-app-namespaces/hooks/post-deploy.sh
  installer/charts/rhtap-app-namespaces/templates/secrets/bitbucket-auth.yaml
  installer/charts/rhtap-app-namespaces/templates/secrets/cosign-pub.yaml
  installer/charts/rhtap-app-namespaces/templates/secrets/github-auth.yaml
  installer/charts/rhtap-app-namespaces/templates/secrets/gitlab-auth.yaml
  installer/charts/rhtap-app-namespaces/templates/secrets/pipelines.yaml
  installer/charts/rhtap-app-namespaces/templates/secrets/rox-api-token.yaml
  installer/charts/rhtap-app-namespaces/templates/secrets/tpa.yaml
Labels: approved, lgtm

#412 RHTAP-4043 update plugins config for jenkins plugin
  installer/charts/rhtap-dh/templates/plugins-content.yaml
Labels: approved, lgtm

#414 Update jenkins plugin content
  installer/charts/rhtap-dh/templates/plugins-content.yaml
Labels: lgtm

#415 fix: template subcommand
  pkg/deployer/helm.go
Labels: approved, lgtm

#416 chore: ignore symlinks to .vscode
  .gitignore
Labels: approved, lgtm
